version: '3.2'

services:
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    hostname: iot.glatzer.eu
    ports:
      - "80:80"
      - "443:443"
    secrets:
     - cert_file
     - cert_key
     - trusted_cert_file
     - dhparam_file
    depends_on:
      - grafana
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /data/certbot/conf/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
      - /data/nginx/htdocs:/var/www/htdocs:ro
    networks:
      iotnet:    
        aliases:
          - iot.glatzer.eu
  influxdb:
    container_name: influxdb
    image: influxdb
    restart: unless-stopped
    hostname: influxdb.iot.glatzer.eu
    ports:
      - "8086:8086"
    volumes:
      - /data/influxdb:/var/lib/influxdb:rw
    secrets:
     - cert_file
     - cert_key
    environment:
      - INFLUXDB_DB=sensordata
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_HTTP_HTTPS_ENABLED=true
      - INFLUXDB_HTTP_HTTPS_CERTIFICATE=/run/secrets/cert_file
      - INFLUXDB_HTTP_HTTPS_PRIVATE_KEY=/run/secrets/cert_key
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_USER_PASSWORD=${INFLUXDB_ADMIN_USER_PASSWORD}
      - INFLUXDB_WRITE_USER=${INFLUXDB_WRITE_USER}
      - INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
      - INFLUXDB_READ_USER=${INFLUXDB_READ_USER}
      - INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}
    networks:
      iotnet:    
        aliases:
          - influxdb.iot.glatzer.eu
  grafana:
    container_name: grafana
    image: grafana/grafana:master
    restart: unless-stopped
    hostname: grafana.iot.glatzer.eu
    ports:
      - "3000:3000"
    volumes:
      - /data/grafana:/var/lib/grafana:rw
    depends_on:
      - influxdb
    secrets:
     - cert_file
     - cert_key
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/run/secrets/cert_file
      - GF_SERVER_CERT_KEY=/run/secrets/cert_key
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_DOMAIN=iot.glatzer.eu
      - GF_SERVER_ROOT_URL=https://iot.glatzer.eu/grafana/
    networks:
      iotnet:    
        aliases:
          - grafana.iot.glatzer.eu
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    hostname: mqtt.iot.glatzer.eu
    ports:
      - "8883:8883"
    secrets:
     - cert_file
     - cert_key
     - dhparam_file
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto_passwd:/mosquitto/config/passwd:ro
      - /data/mqtt/data:/mosquitto/data:rw
      - /data/mqtt/log:/mosquitto/log:rw
    networks:
      iotnet:
        aliases:
          - mqtt.iot.glatzer.eu
  internetstate:
    build: internetstate
    restart: unless-stopped
    networks:
      iotnet:
  covid:
    build: covid
    restart: unless-stopped
    networks:
      iotnet:
secrets:
  cert_file:
    file: /data/certbot/conf/live/iot.glatzer.eu/fullchain.pem
  cert_key:
    file: /data/certbot/conf/live/iot.glatzer.eu/privkey.pem
  trusted_cert_file:
    file: /data/certbot/conf/live/iot.glatzer.eu/chain.pem
  dhparam_file:
    file: /data/certbot/conf/dhparam.pem
networks:
  iotnet: