version: '3.2'

services:
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    hostname: iot.glatzer.eu
    ports:
      - "80:80"
      - "443:443"
    secrets:
     - cert_file
     - cert_key
     - trusted_cert_file
    depends_on:
      - grafana
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
      - ./dhparams.pem:/etc/letsencrypt/dhparams.pem:ro
    networks:
      iotnet:    
        aliases:
          - iot.glatzer.eu

  influxdb:
    container_name: influxdb
    image: influxdb
    restart: unless-stopped
    hostname: influxdb.iot.glatzer.eu
    ports:
      - "8086:8086"
    volumes:
      - /data/influxdb:/var/lib/influxdb:rw
    secrets:
     - cert_file
     - cert_key
    environment:
      - INFLUXDB_DB=sensordata
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_HTTP_HTTPS_ENABLED=true
      - INFLUXDB_HTTP_HTTPS_CERTIFICATE=/run/secrets/cert_file
      - INFLUXDB_HTTP_HTTPS_PRIVATE_KEY=/run/secrets/cert_key
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_USER_PASSWORD=${INFLUXDB_ADMIN_USER_PASSWORD}
      - INFLUXDB_WRITE_USER=${INFLUXDB_WRITE_USER}
      - INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
      - INFLUXDB_READ_USER=${INFLUXDB_READ_USER}
      - INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}
    networks:
      iotnet:    
        aliases:
          - influxdb.iot.glatzer.eu

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    hostname: grafana.iot.glatzer.eu
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - /data/grafana:/var/lib/grafana:rw
    depends_on:
      - influxdb
    secrets:
     - cert_file
     - cert_key
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/run/secrets/cert_file
      - GF_SERVER_CERT_KEY=/run/secrets/cert_key
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_DOMAIN=iot.glatzer.eu
      - GF_SERVER_ROOT_URL=https://iot.glatzer.eu/
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${SMTP_HOST}
      - GF_SMTP_USER=${SMTP_USER}
      - GF_SMTP_PASSWORD=${SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=Grafana
    networks:
      iotnet:    
        aliases:
          - grafana.iot.glatzer.eu

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    hostname: mqtt.iot.glatzer.eu
    ports:
      - "1883:1883"
      - "8883:8883"
    secrets:
     - cert_file
     - cert_key
     - mosquitto_passwd
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - ./dhparams.pem:/etc/letsencrypt/dhparams.pem:ro
      - /data/mqtt/log:/mosquitto/log:rw
      - /data/mqtt/data:/mosquitto/data:rw
    networks:
      iotnet:
        aliases:
          - mqtt.iot.glatzer.eu

secrets:
  cert_file:
    file: /secrets/certbot/live/iot.glatzer.eu/fullchain.pem
  cert_key:
    file: /secrets/certbot/live/iot.glatzer.eu/privkey.pem
  trusted_cert_file:
    file: /secrets/certbot/live/iot.glatzer.eu/chain.pem
  mosquitto_passwd:
    file: /secrets/mosquitto_passwd

networks:
  iotnet: