- name: git clone
  become: no
  git:
    dest: /home/pi/git
    repo: git@github.com:JulianGlatzer/docker-iot.git
    update: yes
    version: master

- name: deploy secrets
  copy:
    src: ./secrets/
    dest: /secrets/
    owner: pi
    group: pi
    mode: '0700'

- name: deploy secrets
  file:
    path: /secrets/mosquitto_passwd
    owner: 1883
    group: 1883
    mode: '0700'

- name: create /data mountpoint
  file:
     path: "/data"
     state: directory
     mode: "777"
     owner: pi
     group: pi

- name: create mosquitto group
  group:
    name: mosquitto
    gid: 1883

- name: create mosquitto user
  user:
    name: mosquitto
    uid: 1883
    group: mosquitto
    shell: /usr/sbin/nologin
    create_home: false

- name: create /data/mqtt directories
  become: yes
  become_user: mosquitto
  file:
     path: "{{ item }}"
     state: directory
     mode: "744"
     owner: mosquitto
     group: mosquitto
  with_items:
    - /data/mqtt
    - /data/mqtt/data
    - /data/mqtt/log

- name: create /data/influxdb directories
  file:
     path: "/data/influxdb"
     state: directory
     mode: "744"
     owner: pi
     group: pi

- name: create /data/grafana directories
  file:
     path: "/data/grafana"
     state: directory
     mode: "744"
     owner: 472
     group: 472

- name: nfs package present
  apt:
    name:
    - nfs-common
    state: present

