{
 "title": "Heating",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"tasmota\" and\n    r._field == \"Temperature\" )\n  |> drop(columns: [\"Endpoint\",\"TempUnit\",\"PressureUnit\",\"boardid\", \"host\",\"topic\",\"deviceid\"])\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"tasmota\" and\n    r._field == \"Humidity\" )\n  |> drop(columns: [\"Endpoint\",\"TempUnit\",\"PressureUnit\",\"boardid\", \"host\",\"topic\",\"deviceid\"])\n"
    }
   ]
  },
  {
   "title": "Heating",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"tasmota\" and\n    r._field == \"FlowTemperature\" or r._field==\"ReturnTemperature\")\n  |> drop(columns: [\"Endpoint\",\"TempUnit\",\"PressureUnit\",\"boardid\", \"host\",\"topic\",\"deviceid\", \"place\"])\n"
    }
   ]
  }
 ]
}